language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polymer-cli web-component-tester
- cd public
- bower install
- polymer lint
script:
- xvfb-run polymer test --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default' --skip-plugin local; fi
env:
  global:
  - secure: DSE8ihiZ12RW2HEG1voOoe/xLiw974LLQ+BLjVcHlSwS3Us/He2CnY/YnTXc1VnHH83yNsA06unvZfFcHxGvJLHEVpE8G8iBrPRuzmewEfoDEW13SZt6L8exKFuJq8UYEyCRNiFLHMpH9WOc+bE6tloVLGvBgYXTcFk/ZFmwy+ckiHOdNMbI4jzMM9+XhBrBAJeGC8vLwo4KorKivZW5Gb2B2vJS5jQPCPNU+vKJyC0vO4VTCBJpjPmnHuozVplZK1+PD+5SoDsZlj4d9/GulFgK/0t3Jv1KMM+4aiym5WZbeoqPZ9taUyDq32Wi+1BBXxoXVNA9YOOsncQMFJHnSRXQJwlCwwWe03DvjfXkAXQFsW8II1rWt0ik/LgX90xJXG3Tp8EqoqwESHk1+8JY8FX8i7eT5KweyNB/wHvNj8qdE8q4rm2IlKTyRtK0ODL5eN7LWaaSFhc6SkbHhhdmOWwSZXyg3AY/PsWAP+zXpLkt/c4BwYc7DT4Yve4emaghbf6UYcPnxMdfctOusjtrF1hKYAbkS4Ft7FVh3IQsi+4eIWcFb3OB3XZ96xamsCNN/qw3xoSARnftgGTUN0OhlXi1594/DdWQ/qhaSkM9QZuTbxlhquAUPggeeif/zJIaG/iU3sC/KiLHm8Cb0Y++9D5xm5ieQz5SvcAPFapUNvg=
  - secure: KshARgd+70ZLRge/kCe9vNvWR2V7KEnWhb5QSARA8ceZU7s1E4QVUGKxZJaK98Xj/XH20IomVpyWJ8LumjYaz48ep8/0fs8+Gx4pVisYNTN7BR9QoIJTODBsjMk9rGJCL/0mXKsCGG1s76xWpPQhhi9nJMhDJT6lsLY4JvofLisImUR/WiWX2g2GeU1TkZJlvRg8LbgMdf4ROpBSdXmRNUi+OaVcxmzQ4pVFnpnhCPfQ6jqDSiQ6F6GkZUu63jc9ONwofp7wsm9QqNx56rbRXMxb2WiM8Bc/ymtPE4K5RizjEL8vQ05eIh6y+xdTcMo//njfFMUcWdjBNYWcPKxGHQfjd5q4x8b10QSP+xNGzR0bMJZa8/gNccGL613bxgNae7nqHwSMll8zi60owAiG3+qiCmQ7OJdwiZV06saU08HnBejsJFzFx7ZB3j5rUdx5VhFQk6U1iMUrcq9N4yoJvvHXLSG7fiaFIi7Or3cEd7rcflWZHRyJY9HlrLLI1ZLDu65UQjuoBv4haP9H2yl/6yeYddYO3mF/J7rFyuLYTLKLUvh42OUx0UCSX4Ww5TZXHdvaYHfTMQATeOqmrmhA67LEicujPwrnrPW7nTYb7lVqvevgvGeMtmcoYl2Ya2/Jqdp37LDTfdCFo4yKQi611JjVX/zSzkD3jBKMCyVnQ9U=
